before_install:
    sudo apt-get -y update;

install:
    sudo apt-get -y install mono-complete;

before_script:
    cd scripts;
    sh generate.sh;

script:
    sh build.sh && exit 1;
    sh test.sh && exit 1;

after_script:
    cd ../;
